### ISSUE TITLE
Setup instructions unclear

### ISSUE THREAD

**Issue by megamorf** [TravisTheTechie/vscode-write-good#1]
I'm sorry to bother you with this but I'd love to use your vscode extension but fail to follow your installation instructions. 

I'd like to use your extension to check markdown files for a jekyll blog and don't know what goes where after installing the extension in vscode. I have nodejs v5.10.1 on my system. I assume I have to cd into the blog repo root and run npm init and then install write-good. But how do I go from there?

Thanks in advance.

**Comment by TravisTheTechie** [comment]
Are you interested in just using this standalone on your blog? This add-on is specifically for [Visual Studio Code](http://code.visualstudio.com). If you just want to use write-good stand alone without Visual Studio Code, then you would need to check in with [write-good](https://github.com/btford/write-good). 

Installing inside Visual Studio Code is just going to the extensions section and finding it, or installing from the marketplace: https://marketplace.visualstudio.com/items?itemName=travisthetechie.write-good-linter.
