### ISSUE TITLE
Duplicate errors in the same document

### ISSUE THREAD

**Issue by jamievlin** [TravisTheTechie/vscode-write-good#10]
How to reproduce:

Create a new file (LaTeX, md, doesn't matter). Write "Unfortunately, not a good way". Save and reload. See 24+ errors saying "Unfortunately can weaken meaning".

On my LaTeX documents, the errors can reach 1000+ errors by this duplicate.

**Comment by TravisTheTechie** [comment]
Hey, this is interesting. I'm not seeing in any configuration I can work through. 

On an existing markdown file (file that the plugin is configured to run on). 

<img width="1297" alt="screen shot 2018-09-08 at 10 41 00 am" src="https://user-images.githubusercontent.com/186225/45257033-107c3380-b354-11e8-85ca-34b926009d31.png">

On a new markdown file. 

<img width="1297" alt="screen shot 2018-09-08 at 10 42 06 am" src="https://user-images.githubusercontent.com/186225/45257037-1d008c00-b354-11e8-8095-9690616a7b7a.png">

On a new tex file, which the plugin is not configured to run on. 

<img width="1297" alt="screen shot 2018-09-08 at 10 44 34 am" src="https://user-images.githubusercontent.com/186225/45257048-39042d80-b354-11e8-9302-9b4f41323186.png">

What version of VS Code are you using, and what other plugins are you using? 1000+ errors does make it hard to use, so I empathize that it's a pretty terrible experience for you.

**Comment by jamievlin** [comment]
Try repeatedely editing and saving. (Can be a minor edit lijke adding spaces or new line). The old error doesn't go away, and new warnings keep popping up.

I use vscode 1.27.1 on Arch Linux with extensions

`akamud.vscode-theme-onedark
akamud.vscode-theme-onelight
alefragnani.Bookmarks
ban.spellright
bierner.color-info
chenxsan.vscode-standardjs
christian-kohler.npm-intellisense
circledev.glsl-canvas
DavidAnson.vscode-markdownlint
donjayamanne.githistory
donjayamanne.jupyter
dracula-theme.theme-dracula
eamodio.gitlens
eg2.vscode-npm-script
Equinusocio.vsc-material-theme
esbenp.prettier-vscode
freetonik.day-night-theme-switcher
HookyQR.beautify
Ionide.Ionide-fsharp
itryapitsin.Scala
James-Yu.latex-workshop
kdarkhan.mips
kirozen.wordcounter
lfurzewaddock.vscode-opn
mads-hartmann.bash-ide-vscode
maptz.regionfolder
ms-python.python
ms-vscode.Theme-MaterialKit
ms-vscode.atom-keybindings
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.PowerShell
naumovs.color-highlight
PKief.material-icon-theme
redhat.java
robertohuertasm.vscode-icons
Shan.code-settings-sync
sidneys1.gitconfig
slevesque.shader
supakornras.asymptote
techer.open-in-browser
travisthetechie.write-good-linter
vscjava.vscode-java-debug
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
wayou.vscode-todo-highlight
wesbos.theme-cobalt2
`

**Comment by TravisTheTechie** [comment]
This appears to be a regression in 1.26. I'll be following up with the VS Code team, I'm not sure if I can mitigate it or not.

**Comment by TravisTheTechie** [comment]
As some notes for myself, the calls to `languages.createDiagnosticCollection` are duplicating the diagnostic collections, I can see the "owner" in the debugger not match, making me thing this is the cause for the mismatch later. 

First load
<img width="1297" alt="screen shot 2018-09-08 at 2 48 43 pm" src="https://user-images.githubusercontent.com/186225/45258931-7d082a00-b376-11e8-94df-9b280f7f8bcb.png">

Later loads (all +1 the owner)
<img width="1297" alt="screen shot 2018-09-08 at 2 48 19 pm" src="https://user-images.githubusercontent.com/186225/45258933-82657480-b376-11e8-9a13-68be80ef1508.png">

**Comment by TravisTheTechie** [comment]
vscode team asserts that the previous behavior was wrong. I think I have a fix for it. https://github.com/TravisTheTechie/vscode-write-good/commit/787af4d3e3d39005684f3e6d88b63d62d4187595. Check out release v0.0.9 which should show up on https://marketplace.visualstudio.com/items?itemName=travisthetechie.write-good-linter any time now.
