### ISSUE TITLE
Installed it in vscode, and doesn't work out of the box

### ISSUE THREAD

**Issue by emonddr** [TravisTheTechie/vscode-write-good#11]
1) Press F1 or CTRL+P and type out > ext install write good linter. 

Doesn't work in my vscode 

I used the Market view in vscode to install it instead

2) After installing the extension, I created an MD file, and wrote a sentence with bad grammar.
     It flagged nothing in the actual file nor in the Problems view.

3) Going into Settings in vscode and searching for write-good, there are a few links
    for settings.json, but when I click on it, it has settings not related to write-good

![image](https://user-images.githubusercontent.com/6864736/58654172-4c419980-82e5-11e9-946d-5d57cc525488.png)

![image](https://user-images.githubusercontent.com/6864736/58654283-86ab3680-82e5-11e9-8acc-c5a29102d359.png)

Please clarify how to set up this extension and its settings for newbies.

Thanks

**Comment by TravisTheTechie** [comment]
Thanks for your report. 

I can update the installation instructions to skip the search step by using the full package name. 

I haven't figured out how I can expose entry in the settings UI directly - but it appears they have changed the default behavior when you click through to edit the `settings.json` file. https://github.com/Microsoft/vscode/issues/65399 shows how to restore the previous behavior where you would some indication into what needed to change. I'll dig into this a bit as it is confusing.

**Comment by atanasj** [comment]
Hi,

I cannot get this extension to work either. What do I need to do?

Cheers,
Atanas.
