### ISSUE TITLE
Extension causes high cpu load (0.1.1)

### ISSUE THREAD

**Issue by garyritchie** [TravisTheTechie/vscode-write-good#12]
- Issue Type: `Performance`
- Extension Name: `write-good-linter`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

[travisthetechie.write-good-linter-unresponsive.cpuprofile.txt](https://github.com/TravisTheTechie/vscode-write-good/files/3702565/travisthetechie.write-good-linter-unresponsive.cpuprofile.txt)

**Comment by TravisTheTechie** [comment]
Can you describe a bit of the instance in which there was high CPU load? Where there a lot of files, large files, or some other description of your setup which causes the issue? 

I'm not 100% sure how to read the cpuprofile, but it appear to be in https://github.com/btford/write-good/blob/master/lib/starts-with-so.js#L12-L13 to me. My first guess is the regex is struggling with specific content. Short term, you can disable the start-with-so (`so: false`) in the configuration passed to write-good and see if that helps.

**Comment by philwinder** [comment]
I agree with this. It gets worse with large documents. You could optimise, truncating the number of returned results or only calling write-good when saving, for example. Doing a scan over a large file is always going to take some time.

**Comment by TravisTheTechie** [comment]
I'm exploring two options here: 

1. Only lint changes, e.g. use https://code.visualstudio.com/api/references/vscode-api#TextDocumentContentChangeEvent on the change event. I think this adds some complexity as it can move other lints around. But maybe I'll be lucky and VS Code will handle that for me. 
2. Add an option to only lint on file save, disabling linting on changes. If I do implement only linting changes on change, saving will likely trigger a full lint to ensure if anything ends up in an odd state it can be fixed.

**Comment by TravisTheTechie** [comment]
v0.1.4 includes a `only-lint-on-save` option. I have half implemented partial linting, but as expected this will require some more work to sort out. The ranges come out all wrong right now. I am going to consider v0.1.4 and `only-lint-on-save` a mitigation for this specific problem.
