### ISSUE TITLE
Colorize differenty errors

### ISSUE THREAD

**Issue by atanasj** [TravisTheTechie/vscode-write-good#15]
Is there a way to apply different colors to the different errors e.g., `weasel`, `passive`, etc?

**Comment by TravisTheTechie** [comment]
Not explicitly, there's a [`DiagnosticSeverity`](https://code.visualstudio.com/api/references/vscode-api#DiagnosticSeverity) (Error, Warning, Information, or Hint -- I use Warning) that can be set and might be able to indirectly pick a color given the severity setting. That's really the best I can think of given the API surface I have to work with.

**Comment by atanasj** [comment]
Okay, thanks for your response and helpful extension!
