### ISSUE TITLE
Lint on rendered md file but not original

### ISSUE THREAD

**Issue by robdefeo** [TravisTheTechie/vscode-write-good#2]
When I use the good-write linter and markdown preview combined it lints only on the rendered file and not the original one. e.g. `filename.md.rendered` is linted but `filename.md` is not. Please advise.

**Comment by TravisTheTechie** [comment]
Apparently I'm a bit behind on this; but I'll try. 

Can you describe your setup a bit more or show me a sample project and steps that reproduces the behavior? I don't have any .rendered files in my repositories, so this isn't something I see. #4 might address this issue if it's just a matter of seeing listing on the .rendered files.

**Comment by TravisTheTechie** [comment]
Released v0.0.6 which should address this. If not feel free to reopen with more details.
