### ISSUE TITLE
Slows down typing to a crawl

### ISSUE THREAD

**Issue by mxstbr** [TravisTheTechie/vscode-write-good#20]
I recently noticed that VS Code sometimes is _very_ slow while typing and it takes seconds for the characters to show up. After profiling when it was slow again (it only starts being slow after using it a bit), this was the result:

<img width="1168" alt="Screenshot 2021-05-10 at 11 40 03" src="https://user-images.githubusercontent.com/7525670/117639677-76b05880-b184-11eb-8468-b93bb0b4bf81.png">

I.e. Write Good Linter was responsible for making VSCode unresponsive :cry: After disabling it, everything was fast again, which is very unfortunate as I quite like this extension!

**Comment by TravisTheTechie** [comment]
I understand your concern here! Can you describe your setup here a bit, so I can poke at limits a bit? I’m guessing there’s a rather sizable markdown file open (or any type of file you have registered to be linted in your configuration). There is an option to just do diff analysis when a change goes through or debounce so it doesn’t process the whole file every keystroke (e.g. only once every few seconds). But they both add a bunch of complexity so I’d rather dive in and see if I have other options first. Even if I did those, we’d still have a first run problem of processing a huge file (if that is in fact the issue).

**Comment by TravisTheTechie** [comment]
With v0.1.5, there's a `write-good.debounce-time-in-ms` configuration setting, which can reduce how often this runs. Dialing that number up will reduce the resources needed while typing.
