### ISSUE TITLE
After activation, write-good lints all filetypes and languages

### ISSUE THREAD

**Issue by JPRuskin** [TravisTheTechie/vscode-write-good#3]
Issue: After activation (by opening a markdown language document) this extension lints *all* documents - including code, etc.

Replication: 
- Install vscode-write-good to VS Code
- Open a markdown document, see that linting is occurring
- Switch to another document (i.e. a script) and see that linting is still occurring

Expected Behavior: Lint *only* markdown (or plaintext) documents.

**Comment by TravisTheTechie** [comment]
Released in v0.0.6, https://marketplace.visualstudio.com/items?itemName=travisthetechie.write-good-linter#overview
