### ISSUE TITLE
Can you explain how to use this?

### ISSUE THREAD

**Issue by mboronin** [TravisTheTechie/vscode-write-good#7]
So I have installed the extension, opened a text, switched to markdown, but can't see any changes

**Comment by TravisTheTechie** [comment]
It doesn't change anything, it does provide hints to things you could change. 

![](https://user-images.githubusercontent.com/186225/31524655-f93c3690-af6f-11e7-8394-1481d1740351.png)

Opening up the README for this project has a couple suggestions, mostly in the legalese of the license. 

Do this help? Is it more clear?

**Comment by mboronin** [comment]
Ok, thank you seems like I tested it with a perfect text, now I can see suggestions.
Can you tell me how to change the settings so it can work with text, not only markdown?

**Comment by TravisTheTechie** [comment]
<img width="647" alt="screen shot 2017-11-01 at 6 21 55 pm" src="https://user-images.githubusercontent.com/186225/32305261-b15dbfb6-bf31-11e7-9d26-281abcee1bb3.png">

If you open up settings, the add-on exposes an option to set the filetypes that it runs for. Just add `"text"` to the array when you select the right setting in autocomplete.
