### ISSUE TITLE
Only activates when Markdown language is selected

### ISSUE THREAD

**Issue by jamievlin** [TravisTheTechie/vscode-write-good#9]
Just to note, but if you're not using Markdown explicitly then the linter won't activate. (This includes LaTeX and other formats). 

A quick ad-hoc fix is to add LaTeX to package activation criteria... 

- Supakorn

**Comment by TravisTheTechie** [comment]
The right fix, after talking to the VS Code folks, is to have it active all the item and just do the analysis based upon configured file types. I haven't done this yet. Let me take a swing at that and see if I can fix this issue more broadly easily. If not, I can add LaTeX as a short term file. I should add plaintext as well if I do that.

**Comment by jamievlin** [comment]
No worries! Thanks for the update. I know this is alot of work already and thanks for your work :)

**Comment by TravisTheTechie** [comment]
Oh a work around you can do, is have an empty markdown file in your project, open it up, then it should still work in LaTeX if you add LaTeX to your settings. You just have to open up a markdown file to activate the plugin. 

```
{
    "write-good.languages": [
        "markdown",
        "latex"
    ]
}
```

**Comment by TravisTheTechie** [comment]
4c627a81bf77914f0e4104edecc1ad2c9ba16384 should fix that. I am publishing a v0.0.8 now.

**Comment by TravisTheTechie** [comment]
Alright, I expected having to change the listener events but that wasn't required. This seems to work for me (using plaintext instead of markdown and getting immediate activation) and is published. Resolving. Please open up an issue if you run into problems.
